spring:
  application:
    name: ms_social_service
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: ms_social_root
  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: root
      password: root
    username: root
    password: root
  jpa:
    d


server:
  port: 8084
axon:
  axonserver:
    servers: localhost
    enabled: false

logging:
  console:
    enabled: true
