services:
  ms_iam_db:
    container_name: ms_iam_database
    image: postgres:18
    env_file:
      - ../env/.env.iam
    ports:
      - "5432:5432"
    volumes:
      - D:/data/iam/postgresql:/var/lib/postgresql/data
  ms_iam_redis:
    container_name: ms_iam_redis
    image: redis:8
    env_file:
      - ../env/.env.iam
    ports:
      - "6379:6379"
    volumes:
      - D:/data/iam/redis:/data

networks:
  ms_dialo_backend:
    driver: bridge