services:
  ms_social_database:
    container_name: ms_social_database
    image: neo4j:2026
    env_file:
      - .env.social
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - D:/data/social/neo4j:/data

networks:
  micro-net:
    external: false