services:
  ms_rabbitmq:
    container_name: ms_rabbitmq
    image: rabbitmq:4-management
    env_file:
      - ../env/.env.rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - D:/data/rabbitmq:/var/lib/rabbitmq

networks:
  ms_dialo_backend:
    driver: bridge